In [1]:
import numpy as np
import pandas as pd
from bokeh.plotting import show

from sompy.sompy_isom import SOMFactory as smf
from sompy.visualization.viz_functions import Visualization_func
from sompy.visualization.comp_planes import som_cplanes
from sompy.visualization.hitmaps import som_hitmap
from sompy.aux_fun import aux_fun

In [2]:
file = open('spherical_data.csv')
n_array = np.genfromtxt(file, delimiter=',',skip_header=1)
data = pd.read_csv('spherical_data.csv')
file.close()

comp_names = list(data.columns)

In [3]:
sm = smf.build(n_array,normalization='range',initialization='pca',mapshape="planar",lattice="hexa",neighborhood='gaussian',
          training='batch',component_names=comp_names)

In [4]:
sm.som_lininit()

sm.train(n_job = 1, shared_memory = False, verbose='info',train_rough_len=200, train_finetune_len=200,
                  train_len_factor=1) # To give train parameters and to train the SOM

 pca_linear_initialization took: 0.008000 seconds
 som_lininit took: 0.010000 seconds
 Training...
 Rough training...
 radius_ini: 1.000000 , radius_final: 1.000000, trainlen: 200

 epoch: 1 ---> elapsed time:  0.001000, quantization error: 0.282688

 epoch: 2 ---> elapsed time:  0.001000, quantization error: 0.268786

 epoch: 3 ---> elapsed time:  0.000000, quantization error: 0.256768

 epoch: 4 ---> elapsed time:  0.001000, quantization error: 0.235844

 epoch: 5 ---> elapsed time:  0.001000, quantization error: 0.214983

 epoch: 6 ---> elapsed time:  0.001000, quantization error: 0.215124

 epoch: 7 ---> elapsed time:  0.001000, quantization error: 0.213354

 epoch: 8 ---> elapsed time:  0.002000, quantization error: 0.212676

 epoch: 9 ---> elapsed time:  0.001000, quantization error: 0.212080

 epoch: 10 ---> elapsed time:  0.001000, quantization error: 0.212945

 epoch: 11 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 12 ---> elapsed time:  0.001000, quanti

 epoch: 114 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 115 ---> elapsed time:  0.000000, quantization error: 0.212114

 epoch: 116 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 117 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 118 ---> elapsed time:  0.002000, quantization error: 0.212114

 epoch: 119 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 120 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 121 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 122 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 123 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 124 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 125 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 126 ---> elapsed time:  0.000000, quantization error: 0.212114

 epoch: 127 ---> elapsed time:  0.000000, quantization error: 0.

 epoch: 28 ---> elapsed time:  0.002000, quantization error: 0.212114

 epoch: 29 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 30 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 31 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 32 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 33 ---> elapsed time:  0.002000, quantization error: 0.212114

 epoch: 34 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 35 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 36 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 37 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 38 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 39 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 40 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 41 ---> elapsed time:  0.002000, quantization error: 0.212114

 epoch

 epoch: 143 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 144 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 145 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 146 ---> elapsed time:  0.000000, quantization error: 0.212114

 epoch: 147 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 148 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 149 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 150 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 151 ---> elapsed time:  0.002000, quantization error: 0.212114

 epoch: 152 ---> elapsed time:  0.002000, quantization error: 0.212114

 epoch: 153 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 154 ---> elapsed time:  0.000000, quantization error: 0.212114

 epoch: 155 ---> elapsed time:  0.001000, quantization error: 0.212114

 epoch: 156 ---> elapsed time:  0.001000, quantization error: 0.

In [5]:
# Visualizations

# Component planes
vis = Visualization_func(sm)
vis.plot_cplanes()

Loading BokehJS ...

In [6]:
axf = aux_fun()
hits = axf.som_hits(sm, sm._data)

In [7]:
# Hit maps
vis.plot_hitmap(hits, 'all', clr='red')

Loading BokehJS ...

In [8]:
# Umatrix

from copy import deepcopy
som_4umatrix = deepcopy(sm)
som_4umatrix.set_codebook_matrix(vis.codebook)

U = axf.som_umat(som_4umatrix, comp='all')   # Using denormalized codebook
vis.plot_umat(U)

Loading BokehJS ...

In [9]:
hits2 = axf.som_hits(sm, sm._data)
hits2[0] = 1
hits2[1:-1] = 0
vis.plot_hitmap(hits2, comp='all', clr='black')

Loading BokehJS ...

In [10]:
id_n = np.where(vis.codebook[:,-1]>18)
id_n

(array([ 0,  4,  5,  6, 11, 12, 18, 19, 24, 25], dtype=int64),)

In [11]:
hits3 = hits2.copy()
hits3[:] = 0
hits3[id_n] = 1
hits3

array([1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0])

In [12]:
vis.plot_hitmap(hits3, comp='all', clr='black')

Loading BokehJS ...

In [13]:
vis.plot_hitmap(hits3, comp=2, clr='black')

Loading BokehJS ...

In [14]:
vis.plot_hitmap(hits3, comp=[0,2], clr='black')

Loading BokehJS ...

In [15]:
U1 = axf.som_umat(som_4umatrix, comp=2)   # Using denormalized codebook
vis.plot_umat(U1)

Loading BokehJS ...

In [16]:
hits4 = hits2.copy()
hits4[:] = 0
hits4[id_n] = 1
hits4[4] = 3
hits4

array([1, 0, 0, 0, 3, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0])

In [17]:
vis.plot_hitmap(hits4, comp='all', clr='black')

Loading BokehJS ...

In [18]:
# Topographic error after training
axf.topographic_error(sm)

0.0

In [19]:
# Quantization error after training
axf.quantization_error(sm,sm._data)

0.21211389503999412